import React from 'react';
    import { motion } from 'framer-motion';
    import { FileText, AlertTriangle } from 'lucide-react';

    const TermsOfServicePage = () => {
        const sectionVariants = {
            hidden: { opacity: 0, y: 20 },
            visible: { opacity: 1, y: 0, transition: { duration: 0.6, ease: "easeOut", staggerChildren: 0.2 } },
        };

        const itemVariants = {
            hidden: { opacity: 0, y: 10 },
            visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
        };
        return (
            <div className="bg-neutral-50 py-16 md:py-24">
                <div className="container mx-auto px-4">
                    <motion.div
                        className="max-w-3xl mx-auto bg-white p-8 md:p-12 rounded-xl shadow-xl"
                        initial="hidden"
                        animate="visible"
                        variants={sectionVariants}
                    >
                        <motion.div className="flex items-center mb-8" variants={itemVariants}>
                            <FileText className="w-10 h-10 mr-4 text-primary" />
                            <h1 className="text-3xl md:text-4xl font-bold text-neutral-800">Terms of Service</h1>
                        </motion.div>

                        <motion.section className="mb-6" variants={itemVariants}>
                            <h2 className="text-xl font-semibold text-neutral-700 mb-2">1. Agreement to Terms</h2>
                            <p className="text-neutral-600 leading-relaxed">
                                By using the services offered by myTradeSolutions ("Service"), you are agreeing to be bound by the following terms and conditions ("Terms of Service"). We reserve the right to update and change the Terms of Service from time to time without notice.
                            </p>
                        </motion.section>

                        <motion.section className="mb-6" variants={itemVariants}>
                            <h2 className="text-xl font-semibold text-neutral-700 mb-2">2. Description of Service</h2>
                            <p className="text-neutral-600 leading-relaxed">
                                myTradeSolutions provides on-site physical inspection and verification services. This includes, but is not limited to, product quality checks, seller/buyer verification, real estate walkthroughs, and document validation based on physical presence and observation.
                            </p>
                        </motion.section>

                        <motion.section className="mb-6" variants={itemVariants}>
                            <h2 className="text-xl font-semibold text-neutral-700 mb-2">3. Service Limitations and Disclaimer</h2>
                            <div className="flex items-start p-4 bg-amber-50 border border-amber-200 rounded-lg mt-4">
                                <AlertTriangle className="w-8 h-8 mr-3 text-amber-500 mt-1 flex-shrink-0" />
                                <div>
                                    <h3 className="text-lg font-semibold text-amber-700 mb-1">Critical Service Clarification</h3>
                                    <p className="text-amber-600 leading-relaxed text-sm">
                                        Our services consist solely of physical verification activities. We do not conduct legal due diligence, authenticate legal documents, or confirm legal ownership status. Any reports, media (photos/videos), or findings provided are based on direct physical observation at the specified time and location of the inspection. These materials are intended for informational purposes to reflect the physical state or presence observed.
                                    </p>
                                    <p className="text-amber-600 leading-relaxed text-sm mt-2">
                                        The documents and findings generated by myTradeSolutions are NOT to be considered or used as legal evidence, official certifications of authenticity, or proof of legal standing or ownership. myTradeSolutions explicitly disclaims any liability or responsibility for the interpretation or use of its reports for legal purposes. We hold no ownership of authentication for the items or information beyond their physical assessment at the inspection time. Clients are responsible for seeking independent legal counsel for any legal verification or due diligence requirements.
                                    </p>
                                </div>
                            </div>
                        </motion.section>

                        <motion.section className="mb-6" variants={itemVariants}>
                            <h2 className="text-xl font-semibold text-neutral-700 mb-2">4. Client Responsibilities</h2>
                            <p className="text-neutral-600 leading-relaxed">
                                You are responsible for providing accurate and complete information required for the service. You agree to ensure that our inspectors have safe and lawful access to the inspection site.
                            </p>
                        </motion.section>
                        
                        <motion.section className="mb-6" variants={itemVariants}>
                            <h2 className="text-xl font-semibold text-neutral-700 mb-2">5. Payment and Fees</h2>
                            <p className="text-neutral-600 leading-relaxed">
                                Fees for services will be as per the pricing agreed upon at the time of booking. Payment is due as specified in the invoice or booking confirmation.
                            </p>
                        </motion.section>

                        <motion.section className="mb-6" variants={itemVariants}>
                            <h2 className="text-xl font-semibold text-neutral-700 mb-2">6. Limitation of Liability</h2>
                            <p className="text-neutral-600 leading-relaxed">
                                To the maximum extent permitted by law, myTradeSolutions shall not be liable for any indirect, incidental, special, consequential or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.
                            </p>
                        </motion.section>

                        <motion.section variants={itemVariants}>
                            <h2 className="text-xl font-semibold text-neutral-700 mb-2">7. Governing Law</h2>
                            <p className="text-neutral-600 leading-relaxed">
                                These Terms shall be governed and construed in accordance with the laws of Saudi Arabia, without regard to its conflict of law provisions.
                            </p>
                        </motion.section>

                        <motion.p className="text-xs text-neutral-500 mt-10 text-center" variants={itemVariants}>
                            Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                        </motion.p>
                    </motion.div>
                </div>
            </div>
        );
    };

    export default TermsOfServicePage;